# This config file is set up to -

# execute scripts on your local machine in Chrome browser in desktop mode and default resolution:

configuration.profiles=web/desktop/chrome
web.driver.chrome.experimental-options={"prefs": {"profile": {"password_manager_leak_detection": false}}}

# pick up suite related properties from 'demo' suite folder:

configuration.suites=demo

# pick up environment related properties from 'saucedemo' environment folder:

configuration.environments=saucedemoMroz
