# Put here properties that will be used for local debugging and local test runs.
# The properties defined in this file override any properties set in dedicated folders
configuration.suites=training

#variables.baselineAction=COMPARE_AGAINST
variables.baselineAction=ESTABLISH
ui.visual.baseline-storage.filesystem.folder=C:/repo2/project1/vividus-training/src/main/resources/baselines